USE DIVERSOS_TESTES;
GO

IF(EXISTS(SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'TB_COMPACT_DISC'))
	DROP TABLE TOPAZ.TB_COMPACT_DISC;

IF(EXISTS(SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'TB_FAIXA'))
	DROP TABLE TOPAZ.TB_FAIXA;

IF(EXISTS(SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'TB_GENERO'))
	DROP TABLE TOPAZ.TB_GENERO;

IF(EXISTS(SELECT SCHEMA_ID FROM SYS.SCHEMAS WHERE NAME = 'TOPAZ'))
	DROP SCHEMA TOPAZ;

CREATE SCHEMA TOPAZ;
GO

CREATE TABLE TOPAZ.TB_GENERO 
(
	ID						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	NOME					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE TOPAZ.TB_FAIXA 
(
	ID						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TITULO					NVARCHAR(50) NOT NULL,
	DURACAO					DECIMAL(3, 2) NOT NULL,
	ARTISTA					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE TOPAZ.TB_COMPACT_DISC 
(
	ID						UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	TB_FAIXA_ID				UNIQUEIDENTIFIER NOT NULL,
	TB_GENERO_ID			UNIQUEIDENTIFIER NOT NULL,
	TITULO					NVARCHAR(50) NOT NULL,
	DATA_CADASTRO			DATETIME NOT NULL DEFAULT GETDATE(),
	INDEX IDX_TB_COMPACT_DISC_TB_FAIXA_ID(TB_FAIXA_ID),
	INDEX IDX_TB_COMPACT_DISC_TB_GENERO_ID(TB_GENERO_ID),
	FOREIGN KEY(TB_FAIXA_ID) REFERENCES TOPAZ.TB_FAIXA(ID),
	FOREIGN KEY(TB_GENERO_ID) REFERENCES TOPAZ.TB_GENERO(ID),
	CONSTRAINT UC_TB_COMPACT_DISC UNIQUE (ID, TB_FAIXA_ID, TB_GENERO_ID, TITULO)
);

INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'ROCK');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'SAMBA');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'SERTANEJO');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'MPB');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'HIP HOP');
INSERT INTO TOPAZ.TB_GENERO (ID, NOME) VALUES (NEWID(), 'RAP');

